# Generated by Django 2.2.5 on 2019-09-22 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=255, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
    ]
